### ISSUE TITLE
Symbol not found: _objc_alloc_init

### ISSUE THREAD

**Issue by cellcrowd** [libgdx/libgdx#6413]
#### Issue details
After updating to LibGDX 1.9.15-SNAPSHOT, the app crashes on iOS < 13 with this error:
```
dyld: lazy symbol binding failed: Symbol not found: _objc_alloc_init
  Referenced from: /Users/cellcrowd/Library/Developer/CoreSimulator/Devices/D387FB2F-A92D-44F9-A7DB-D3FCB8AAF3D1/data/Containers/Bundle/Application/EE9AFCF3-4FF3-4F64-91D7-08387A843DC3/IOSLauncher.app/IOSLauncher
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation

dyld: Symbol not found: _objc_alloc_init
  Referenced from: /Users/cellcrowd/Library/Developer/CoreSimulator/Devices/D387FB2F-A92D-44F9-A7DB-D3FCB8AAF3D1/data/Containers/Bundle/Application/EE9AFCF3-4FF3-4F64-91D7-08387A843DC3/IOSLauncher.app/IOSLauncher
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation
```

#### Reproduction steps/code
Updated to LibGDX 1.9.15-SNAPSHOT from LibGDX 1.9.13 (=no crashes)
Cleaned project, cleared MobiVM and IntelliJ caches

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.15-SNAPSHOT
App crashes with given error on iOS < 13. Works on iOS >= 13

LibGDX 1.9.14 
Compiling fails with duplicate symbol errors which has been reported and identified as a regression at https://github.com/libgdx/libgdx/issues/6402

LibGDX 1.9.13
Works on all iOS versions

All of the above using:
MobiVM 2.3.12
IntelliJ 2020.2.4 (community edition)
XCode 12.4

Several Firebase frameworks are added:
https://github.com/dkimitsa/robovm-robopods/issues/8

#### Please select the affected platforms
- [ ] Android
- [X] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by yajirobe69** [comment]
Can confirm, this is still happening with current 1.9.15-SNAPSHOT. Which is too bad since, I kinda need this snapshot version for the fix for logical pixels vs raw pixels

**Comment by Tom-Ski** [comment]
What you provided isn't the same as #6402 , there are no duplicate symbols in the log you reported. What is your version of MacOS and xcode?

**Comment by cellcrowd** [comment]
Be advised the log is from 1.9.15-SNAPSHOT. For 1.9.14 I get the duplicate symbol errors. I am using XCode 12.4 on MacOS Catalina 10.15.7

**Comment by obigu** [comment]
I've tried to reproduce the described issue and haven't been able to replicate but have also found an issue when running on on iOS 12.

On:
- iOS 12.4 Simulator (not tested on iOS 12 device)
- IntelliJ 2020.3.2
- MobiVM 2.3.12 IDEA plugin
- Xcode 12.4
- MacOS 11.2.1
- ALL versions of libGDX from 1.9.10 to 1.9.15-SNAPSHOT (excluding 1.9.14 which fails when building it due to #6402)

The app crashes on startup with the "silent" (no description/stacktrace) log:
`(UIKitApplication:com.mygdx.game[0x276b][6115][8443]) Service exited due to SIGABRT`

It fails when `IOSApplication` creates the `Audio` implementation on `OALSimpleAudio audio = OALSimpleAudio.sharedInstance();`.

All tests have been performed on a newly created project using latest available Gdx-Setup (with Desktop, Android, iOS and Box2D modules) . @cellcrowd For further reports/follow-ups I suggest you use a blank project to make sure we all test the same thing.

The issue doesn't occur when running on iOS 14.4 Simulator.

I can't discard it's an environment issue but i've made sure to clean up all caches before every test. @cellcrowd It would be great if you could run this on your environment see if we get consistent results.

**Comment by yajirobe69** [comment]
@obigu that's the issue he's describing though?

> LibGDX 1.9.15-SNAPSHOT App crashes with given error on iOS < 13. Works on iOS >= 13

I can confirm this ^, ios only runs on my iOS 14 iPad (unsure of ios 13) and does run fine on iOS 12 iPad

regardless, yes I get the same error you're describing, about the initiation of the Audio implementation

**Comment by obigu** [comment]
> @obigu that's the issue he's describing though?
> 
> > LibGDX 1.9.15-SNAPSHOT App crashes with given error on iOS < 13. Works on iOS >= 13
> 

It doesn't seem to be the same.
1. The stacktrace is different (he actually gets a stacktrace which I don't)
2. It works for him on libGDX 1.9.13

> regardless, yes I get the same error you're describing, about the initiation of the Audio implementation

On what iOS versions and libGDX versions?

**Comment by yajirobe69** [comment]
I get the same crash when running latest snapshot on iOS 14 (haven't tested on 13) but can confirm it works fine on an iOS 12 device

I get the same `(UIKitApplication:com.mygdx.game[0x276b][6115][8443]) Service exited due to SIGABRT`

Upon checking the device logs in Xcode it's the messy `Symbol not found: _objc_alloc_init` mentioning `OALSimpleAudio `

```
Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   dyld                           0x0000000103f30b14 __terminate_with_payload + 8
1   dyld                           0x0000000103f2f948 abort_with_payload_wrapper_internal + 132
2   dyld                           0x0000000103f2f958 fcntl + 0
3   dyld                           0x0000000103ef08f4 dyld::fastBindLazySymbol+ 18676 (ImageLoader**, unsigned long) + 0
4   dyld                           0x0000000103ef0a10 dyld::fastBindLazySymbol+ 18960 (ImageLoader**, unsigned long) + 284
5   libdyld.dylib                 0x00000001f6afcbd0 dyld_stub_binder + 60
6   IOSLauncher                   0x00000001010c59d8 +[OALSimpleAudio sharedInstanceSynch] + 2005464 (OALSimpleAudio.m:69)
7   IOSLauncher                   0x0000000101297d78 0x100edc000 + 3915128
8   IOSLauncher                   0x000000010129771c 0x100edc000 + 3913500
9   IOSLauncher                   0x00000001012976cc 0x100edc000 + 3913420
10  IOSLauncher                   0x0000000101297414 [J]com.badlogic.gdx.backends.iosrobovm.objectal.OALIOSAudio.<init>(Lcom/badlogic/gdx/backends/iosrobovm/IOSApplicationConfiguration;)V + 3912724 (OALIOSAudio.java:35)
11  IOSLauncher                   0x00000001012801d4 [J]com.badlogic.gdx.backends.iosrobovm.IOSApplication.createAudio(Lcom/badlogic/gdx/backends/iosrobovm/IOSApplicationConfiguration;)Lcom/badlogic/gdx/backends/iosrobovm/IOSAudio; + 3817940 (IOSApplication.java:163)
12  IOSLauncher                   0x000000010127ff28 [J]com.badlogic.gdx.backends.iosrobovm.IOSApplication.didFinishLaunching(Lorg/robovm/apple/uikit/UIApplication;Lorg/robovm/apple/uikit/UIApplicationLaunchOptions;)Z + 3817256 (IOSApplication.java:142)
13  IOSLauncher                   0x0000000101282490 [J]com.badlogic.gdx.backends.iosrobovm.IOSApplication$Delegate.didFinishLaunching(Lorg/robovm/apple/uikit/UIApplication;Lorg/robovm/apple/uikit/UIApplicationLaunchOptions;)Z + 3826832 (IOSApplication$Delegate.java:66)
14  IOSLauncher                   0x000000010174dfe4 [J]org.etc.IOSLauncher.didFinishLaunching(Lorg/robovm/apple/uikit/UIApplication;Lorg/robovm/apple/uikit/UIApplicationLaunchOptions;)Z + 8855524 (IOSLauncher.java:144)
```

**Comment by obigu** [comment]
Ok, good to see it's the same issue. 

I'm not sure why it may be that it seems to fail on different libGDX and iOS combinations for the 3 of us.

Here is my matrix:

|  | 1.9.13 | 1.9.15-SNAPSHOT |
|  ---  |  ---   |   ---  |
| **iOS 12**    | Crash  | Crash |
| **iOS 14**    | Ok     | Ok    |

If I understand correctly, this is @cellcrowd 

|  | 1.9.13 | 1.9.15-SNAPSHOT |
|  ---  |  ---   |   ---  |
| **iOS 12**    | Ok  | Crash |
| **iOS 14**    | Ok     | Ok    |

And @yajirobe69  this is your matrix right?

|  | 1.9.13 | 1.9.15-SNAPSHOT |
|  ---  |  ---   |   ---  |
| **iOS 12**    | Ok?  | Ok |
| **iOS 14**    | Ok?     | Crash  |

To discard it's related to the device/iPad OS I've tried testing on iPhone 8 and iPad (8th Gen) simulators and results are consistent

**Comment by Tom-Ski** [comment]
Please try the latest snapshot and let me know how that goes

**Comment by obigu** [comment]
> Please try the latest snapshot and let me know how that goes

It still fails for me but considering it was also failing (and still does) on 1.9.13 in my case, I was not expecting a new build to fix it. Let's see what @cellcrowd and @yajirobe69 say, in the meantime I'll try some other stuff like testing on a new simulator.

**Comment by yajirobe69** [comment]
Had to wait an eternity for Xcode to update from 12 to 12.4, just to confirm that not be an issue

Refreshed snapshot/gradle, cleared cache, compiled, and is now deploying on both my iOS 12 and 14 devices. Seems it's fixed, was something specific changed in the snapshot?

**Comment by Tom-Ski** [comment]
@obigu you are still having issues? What are your problems?

**Comment by obigu** [comment]
@Tom-Ski With the latest SNAPSHOT I'm having the same problems I describe on firs post. Basically a sample new app using Gdx-Setup crashes on startup no matter the libGDX version I use on iOS 12 simulator.

@yajirobe69 From your post I understand you are testing on devices. Can you please test on iOS 12 Simulator (both 1.9.15-SNAPSHOT and 1.9.13)?

**Comment by cellcrowd** [comment]
Using the latest 1.19.15-SNAPSHOT, I too can confirm my app now runs fine without any crashes on simulator 11/12/13/14 and devices 10/11/12/13/14.

For testing on devices, I am using BrowserStack (App Live). They claim to support open source projects so their platform may be a good addition to the libGDX testing pipeline? https://www.browserstack.com/open-source

**Comment by obigu** [comment]
@cellcrowd Ok, good news, feel free to close the issue, I'll keep banging my head against the wall to try to understand what's wrong with my env. 

I think the culprit has to do with the fact that we have migrated to gdx-jnigen to build natives and `-miphoneos-version-min` was being set to `6` instead of `8` which was causing problems. (https://github.com/libgdx/gdx-jnigen/blob/f9be183adefb5fe9c8917a1b83bc7f9cc8961200/gdx-jnigen/src/main/resources/com/badlogic/gdx/jnigen/resources/scripts/build-ios.xml.template#L87) 

@Tom-Ski Thanks for the fix.

**Comment by cellcrowd** [comment]
Closing now, thanks for the effort guys!

**Comment by Tom-Ski** [comment]
@obigu this issue was that new xcode is ignoring that flag. When building with xcodebuild to build the audio backend it was overriding it to latest for the system, 14.2. jnigen was fine when i looked at it, (it does not use xcodebuild to generate natives), and no warnings for versions in logs
