### ISSUE TITLE
FrameBuffer.getColorTexture() not work on desktop 

### ISSUE THREAD

**Issue by d954mas** [libgdx/libgdx#3245]
fboA.getColorBufferTexture() -not work on desktop after libgdx 1.6.2

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.badlogic.gdx.graphics.glutils.FrameBuffer.getColorBufferTexture()Lcom/badlogic/gdx/graphics/GLTexture;
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)

Caused by: java.lang.NoSuchMethodError: com.badlogic.gdx.graphics.glutils.FrameBuffer.getColorBufferTexture()Lcom/badlogic/gdx/graphics/GLTexture;

OS: Debian 8
VGA: Intel HD Graphics 4600 
OpenGL 3.0

**Comment by xoppa** [comment]
That method has been moved to its superclass, which shouldnt be an issue. See https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java#L252. How did you verify that this is an issue with libgdx and not with your project?

**Comment by d954mas** [comment]
Sorry,Issue in my project,in new project this method work.
