### ISSUE TITLE
Build with Gradle  5.4.1 fails

### ISSUE THREAD

**Issue by bobsort** [libgdx/libgdx#5783]
Please ensure you have given all the following requested information in your report.

#### Issue details
```
> Configure project :tests:gdx-tests-android
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018

> Task :extensions:gdx-jnigen:compileJava FAILED
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':extensions:gdx-jnigen:compileJava'.
> Compilation failed; see the compiler error output for details.
```

#### Reproduction steps/code
Downloaded https://github.com/libgdx/libgdx/archive/gdx-parent-1.9.10.tar.gz
Extract to folder, run `Gradle Build` from command line
Gradle is local installation (version 5.4.1)
JDK is Open jdk-12.0.1 (Oracle)

#### Version of LibGDX and/or relevant dependencies
1.9.10

#### Stacktrace
None, Compile fails

#### Please select the affected platforms
None, Compile fails

#### 
Additional notes,
Changed all  `sourceCompatibility` and `targetCompatibility` in all gradle files from 1.6 and 1.7 to 1.8 Most of compile goes through but it fails again with following error

```
> Task :extensions:gdx-bullet:compileJava FAILED
P:\libgdx-gdx-parent-1.9.10\extensions\gdx-bullet\jni\swig-src\collision\com\badlogic\gdx\physics\bullet\collision\Collision.java:148: error: cannot find symbol
  public static void setGContactAddedCallback(SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool value) {
                                              ^
  symbol:   class SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool
  location: class Collision
P:\libgdx-gdx-parent-1.9.10\extensions\gdx-bullet\jni\swig-src\collision\com\badlogic\gdx\physics\bullet\collision\Collision.java:152: error: cannot find symbol
  public static SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool getGContactAddedCallback() {
                ^
  symbol:   class SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool
  location: class Collision
P:\libgdx-gdx-parent-1.9.10\extensions\gdx-bullet\jni\swig-src\dynamics\com\badlogic\gdx\physics\bullet\dynamics\btSimulationIslandManagerMt.java:235: error: cannot find symbol
  public SWIGTYPE_p_f_p_btAlignedObjectArray__p_btSimulationIslandManagerMt__Island___p_btSimulationIslandManagerMt__IslandCallback__void getIslandDispatchFunction() {
         ^
  symbol:   class SWIGTYPE_p_f_p_btAlignedObjectArray__p_btSimulationIslandManagerMt__Island___p_btSimulationIslandManagerMt__IslandCallback__void
  location: class btSimulationIslandManagerMt
P:\libgdx-gdx-parent-1.9.10\extensions\gdx-bullet\jni\swig-src\dynamics\com\badlogic\gdx\physics\bullet\dynamics\btSimulationIslandManagerMt.java:240: error: cannot find symbol
  public void setIslandDispatchFunction(SWIGTYPE_p_f_p_btAlignedObjectArray__p_btSimulationIslandManagerMt__Island___p_btSimulationIslandManagerMt__IslandCallback__void func) {
                                        ^
  symbol:   class SWIGTYPE_p_f_p_btAlignedObjectArray__p_btSimulationIslandManagerMt__Island___p_btSimulationIslandManagerMt__IslandCallback__void
  location: class btSimulationIslandManagerMt
P:\libgdx-gdx-parent-1.9.10\extensions\gdx-bullet\jni\swig-src\collision\com\badlogic\gdx\physics\bullet\collision\Collision.java:149: error: cannot find symbol
    CollisionJNI.gContactAddedCallback_set(SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool.getCPtr(value));
                                           ^
  symbol:   variable SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool
  location: class Collision
P:\libgdx-gdx-parent-1.9.10\extensions\gdx-bullet\jni\swig-src\collision\com\badlogic\gdx\physics\bullet\collision\Collision.java:154: error: cannot find symbol
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool(cPtr, false);
                                    ^
  symbol:   class SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool
  location: class Collision
P:\libgdx-gdx-parent-1.9.10\extensions\gdx-bullet\jni\swig-src\dynamics\com\badlogic\gdx\physics\bullet\dynamics\btSimulationIslandManagerMt.java:237: error: cannot find symbol
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_btAlignedObjectArray__p_btSimulationIslandManagerMt__Island___p_btSimulationIslandManagerMt__IslandCallback__void(cPtr, false);
                                    ^
  symbol:   class SWIGTYPE_p_f_p_btAlignedObjectArray__p_btSimulationIslandManagerMt__Island___p_btSimulationIslandManagerMt__IslandCallback__void
  location: class btSimulationIslandManagerMt
P:\libgdx-gdx-parent-1.9.10\extensions\gdx-bullet\jni\swig-src\dynamics\com\badlogic\gdx\physics\bullet\dynamics\btSimulationIslandManagerMt.java:241: error: cannot find symbol
    DynamicsJNI.btSimulationIslandManagerMt_setIslandDispatchFunction(swigCPtr, this, SWIGTYPE_p_f_p_btAlignedObjectArray__p_btSimulationIslandManagerMt__Island___p_btSimulationIslandManagerMt__IslandCallback__void.getCPtr(func));
                                                                                      ^
  symbol:   variable SWIGTYPE_p_f_p_btAlignedObjectArray__p_btSimulationIslandManagerMt__Island___p_btSimulationIslandManagerMt__IslandCallback__void
  location: class btSimulationIslandManagerMt
Note: P:\libgdx-gdx-parent-1.9.10\extensions\gdx-bullet\src\com\badlogic\gdx\physics\bullet\BulletBase.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
8 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':extensions:gdx-bullet:compileJava'.
> Compilation failed; see the compiler error output for details.
```

**Comment by SimonIT** [comment]
I recommend you to use java 11. With java 11 you don't have to increase the sourceCompatibility and targetCompatibility

**Comment by shatterblast** [comment]
@bobsort You should use Java 8 or 11.  Close this, please.

**Comment by bobsort** [comment]
I can't close it as I can't even login to github anymore. you know because Microsoft bought it.


 On Wednesday, March 25, 2020, 02:51:21 AM GMT+8, Wes Lange <notifications@github.com> wrote:

@bobsort You should use Java 8 or 11. Close this, please.

**Comment by bobsort** [comment]
Also, I decided I will not use this anymore, 
When a library doesn't support your environment, normally you don't change your environment, you change the library.

**Comment by SimonIT** [comment]
Tom-Ski changed the sourceCompatibility and targetCompatibility in https://github.com/libgdx/libgdx/commit/de77fee09ca14d0b2a02672ba93fa6871f1b7e05, so it might work now without changing the jdk
